## HWK 4 Yuhui Ren

__Step 1:__<br>Use our “titanic” dataset in homework #3, and split data in the same way you did in homework #3 as training and test sets

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [73]:
data = pd.read_csv("titanic.csv")[['pclass','sex','age','sibsp','survived']]
data.dropna(axis=0, how='any', inplace=True)    # Omit all NA examples
data.replace({"pclass":{"1st":1, "2nd":2, "3rd":3}}, inplace=True)
data.replace({"sex":{"male":1, "female":2}}, inplace=True)
data.head()

pclass  sex      age  sibsp  survived
0       1    2  29.0000      0         1
1       1    1   0.9167      1         1
2       1    2   2.0000      1         0
3       1    1  30.0000      1         0
4       1    2  25.0000      1         0

In [59]:
y = data["survived"]
X = data[['pclass','sex','age','sibsp']]
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,shuffle=True)

__Step 2:__<br>Fit a neural network using independent variables ‘pclass + sex + age + sibsp’ and dependent variable ‘survived’. <br>Omit all NA examples. Use 2 hidden layers and set the activation functions for both the hidden and output layer to be the sigmoid function. <br>Set “solver” parameter as either SGD (stochastic gradient descend) or Adam (similar to SGD but optimized performance with mini batches). <br>You can adjust parameter “alpha” for regularization (to control overfitting) and other parameters such as “learning rate” and “momentum” as needed.

In [46]:
from sklearn.neural_network import MLPClassifier

In [61]:
# Model 1

clf_1 = MLPClassifier(hidden_layer_sizes=(50,50), activation='logistic', solver='adam', alpha=0.0001)
clf_1.fit(X_train, y_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=(50, 50))

In [62]:
# Model 2

clf_2 = MLPClassifier(hidden_layer_sizes=(150,150), activation='logistic', solver='adam', alpha=0.0001)
clf_2.fit(X_train, y_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=(150, 150))

__Step 3:__<br>Check the performance of the model: in-sample and out-of- sample accuracy, defined as
<br>in-sample percent survivors correctly predicted (on training set)
<br>in-sample percent fatalities correctly predicted (on training set)
<br>out-of-sample percent survivors correctly predicted (on test set)
<br>out-of-sample percent fatalities correctly predicted (on test set)
<br>Please try two different network structures (i.e., number of neurons at each hidden layer) and show their respective accuracy.

In [47]:
from sklearn.metrics import confusion_matrix

In [63]:
# Model 1

y_hat_train = clf_1.predict(X_train)
tn, fp, fn, tp = confusion_matrix(y_train, y_hat_train).ravel()    # on training set
print("in‐sample survivors accuracy (on training set):{:.3f}".format(tp/(tp+fn)))
print("in‐sample fatalities accuracy (on training set):{:.3f}".format(tn/(fp+tn)))


in‐sample survivors accuracy (on training set):0.744
in‐sample fatalities accuracy (on training set):0.830


In [64]:
# Model 1

y_hat_test = clf_1.predict(X_test)
tn, fp, fn, tp = confusion_matrix(y_test, y_hat_test).ravel()    # on testing set
print("out‐of‐sample survivors accuracy (on testing set):{:.3f}".format(tp/(tp+fn)))
print("out‐of‐sample fatalities accuracy (on testing set):{:.3f}".format(tn/(fp+tn)))

out‐of‐sample survivors accuracy (on testing set):0.772
out‐of‐sample fatalities accuracy (on testing set):0.870


In [65]:
# Model 2

y_hat_train = clf_2.predict(X_train)
tn, fp, fn, tp = confusion_matrix(y_train, y_hat_train).ravel()    # on training set
print("in‐sample survivors accuracy (on training set):{:.3f}".format(tp/(tp+fn)))
print("in‐sample fatalities accuracy (on training set):{:.3f}".format(tn/(fp+tn)))

in‐sample survivors accuracy (on training set):0.609
in‐sample fatalities accuracy (on training set):0.930


In [66]:
# Model 2

y_hat_test = clf_2.predict(X_test)
tn, fp, fn, tp = confusion_matrix(y_test, y_hat_test).ravel()    # on testing set
print("out‐of‐sample survivors accuracy (on testing set):{:.3f}".format(tp/(tp+fn)))
print("out‐of‐sample fatalities accuracy (on testing set):{:.3f}".format(tn/(fp+tn)))

out‐of‐sample survivors accuracy (on testing set):0.646
out‐of‐sample fatalities accuracy (on testing set):0.947


__Step 4:__<br>Compare the in-sample and out-of-sample accuracy (as defined in step 3) with the pruned decision tree obtained in homework #3. 
<br>You can either use a table or a figure to compare the accuracy of the two learning algorithms

In [74]:
df = pd.DataFrame({'Tree_pruned':[0.756,0.845,0.641,0.799],\
                  'NN_small':[0.744, 0.830, 0.772, 0.870], \
                   'NN_large':[0.609, 0.930, 0.646, 0.947]},\
                 index=['in‐sample survivors accuracy','in‐sample fatalities accuracy',\
                        'out‐of‐sample survivors accuracy','out‐of‐sample fatalities accuracy'])
df

Tree_pruned  NN_small  NN_large
in‐sample survivors accuracy             0.756     0.744     0.609
in‐sample fatalities accuracy            0.845     0.830     0.930
out‐of‐sample survivors accuracy         0.641     0.772     0.646
out‐of‐sample fatalities accuracy        0.799     0.870     0.947

For both in‐sample fatalities accuracy and out‐of‐sample fatalities accuracy, neural network (larger one) has the highest accuray, which are 0.930 and 0.947. <br>For in‐sample survivors accuracy, the pruned decision gets the highest accuracy which is 0.756, but in‐sample survivors accuracy from the smaller neural network is 0.744, which is only 1.2% lower, I think this does not lose too much. <br>For out‐of‐sample survivors accuracy, the smaller neural network get the highest accuracy, which is 0.772. <br>To conclude, I think in this case neural network outperform decision tree.